export const SOL_MINT = "So11111111111111111111111111111111111111112";
export const USDC_SOL_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";

export type SolanaToken = {
  mint: string;
  symbol: string;
  name: string;
  decimals: number;
  logo?: string;
  verified: boolean;
  tags: string[];
  liquidity: number;
};

export const SOLANA_CORE_FALLBACK: SolanaToken[] = [
  {
    mint: SOL_MINT,
    symbol: "SOL",
    name: "Solana",
    decimals: 9,
    logo: "https://assets.coingecko.com/coins/images/4128/standard/solana.png",
    verified: true,
    tags: ["verified"],
    liquidity: 0,
  },
  {
    mint: USDC_SOL_MINT,
    symbol: "USDC",
    name: "USD Coin",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/6319/standard/usdc.png",
    verified: true,
    tags: ["verified"],
    liquidity: 0,
  },
  {
    mint: "Es9vMFrzaCERmJfrF4H2FYDkUBwWPgn6jPJNPQXzJXrY",
    symbol: "USDT",
    name: "Tether USD",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/325/standard/Tether.png",
    verified: true,
    tags: ["verified", "stablecoin"],
    liquidity: 0,
  },
  {
    mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
    symbol: "JUP",
    name: "Jupiter",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/34188/standard/jup.png",
    verified: true,
    tags: ["verified"],
    liquidity: 0,
  },
  {
    mint: "DezXAZ8z7PnrnRJjz3wXBoRgixCa6iB7hUAs6ZnWKFA",
    symbol: "BONK",
    name: "Bonk",
    decimals: 5,
    logo: "https://assets.coingecko.com/coins/images/28600/standard/bonk.jpg",
    verified: true,
    tags: ["verified", "community"],
    liquidity: 0,
  },
  {
    mint: "HZ1JovNiVvGrGNiiYvEozEVgZ58xaU3RKwX8eACQBCt3",
    symbol: "PYTH",
    name: "Pyth Network",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/31924/standard/pyth.png",
    verified: true,
    tags: ["verified"],
    liquidity: 0,
  },
  {
    mint: "jtojtomepa8beP8AuQc6eXt5FriJwfFMwQx2v2f9mCL",
    symbol: "JTO",
    name: "Jito",
    decimals: 9,
    logo: "https://assets.coingecko.com/coins/images/33228/standard/jto.png",
    verified: true,
    tags: ["verified"],
    liquidity: 0,
  },
  {
    mint: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5i9zQA5fwmqAQ",
    symbol: "RAY",
    name: "Raydium",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/13928/standard/PSigc4ie_400x400.jpg",
    verified: true,
    tags: ["verified", "defi"],
    liquidity: 0,
  },
  {
    mint: "orcaEKTdK7LKz57vaAYr9QeNsHPEBFr8DKhNUxW3x2",
    symbol: "ORCA",
    name: "Orca",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/17547/standard/Orca_Logo.png",
    verified: true,
    tags: ["verified", "defi"],
    liquidity: 0,
  },
  {
    mint: "mSoLzYCxHdYgdzU2MeQGvDhJgSP7tNqpnH3h7vDgkkN",
    symbol: "mSOL",
    name: "Marinade Staked SOL",
    decimals: 9,
    logo: "https://assets.coingecko.com/coins/images/17752/standard/mSOL.png",
    verified: true,
    tags: ["verified", "lst"],
    liquidity: 0,
  },
  {
    mint: "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn",
    symbol: "JitoSOL",
    name: "Jito Staked SOL",
    decimals: 9,
    logo: "https://assets.coingecko.com/coins/images/28046/standard/JitoSOL-200.png",
    verified: true,
    tags: ["verified", "lst"],
    liquidity: 0,
  },
  {
    mint: "EKpQGSJtjMFqKZ9KQanSqYXRcF8fBopzLUnEKAzoZg",
    symbol: "WIF",
    name: "dogwifhat",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/33566/standard/dogwifhat.jpg",
    verified: true,
    tags: ["verified", "community"],
    liquidity: 0,
  },
  {
    mint: "PUMPcmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn",
    symbol: "PUMP",
    name: "Pump.fun",
    decimals: 6,
    logo: "https://assets.coingecko.com/coins/images/55056/standard/pump.jpg",
    verified: true,
    tags: ["verified", "pump-fun"],
    liquidity: 0,
  },
  {
    mint: "KMNo3nJsBXfcpJTVhZcXLW7RmTwTt4GVFE7suUBo9sS",
    symbol: "KMNO",
    name: "Kamino",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/b3b9a0026bec75db0e4ecb6e023901a812dad85d3ffa1d2ec8b3a53ca498da31?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "defi"],
    liquidity: 0,
  },
  {
    mint: "2zMMhcVQEXDtdE6vsFS7S7D5oUodfJHE8vd1gnBouauv",
    symbol: "PENGU",
    name: "Pudgy Penguins",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/9d5188f603b49ab02f7a75e5d2c2959ec2947c98181501fb11688672e9394efd?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
  {
    mint: "ukHH6c7mMyiWCf1b9pnWe25TSpkDDt3H5pQZgZ74J82",
    symbol: "BOME",
    name: "BOOK OF MEME",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/1fdb1c93b76e5aed7324c2c541558fd75fe7ffb3d0d0fb9ee8370cbac5890e4e?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
  {
    mint: "Dz9mQ9NzkBcCsuGPFJ3r1bS4wgqKMHBPiVuniW8Mbonk",
    symbol: "USELESS",
    name: "Useless Coin",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/4f8af59f26d45252fb4379d4b1a1e61d0b419fd34dab2ec9f3ba77585d1783cb?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
  {
    mint: "MEW1gQWJ3nEXg2qgERiKu7FAFj79PHvQVREQUzScPP5",
    symbol: "MEW",
    name: "cat in a dogs world",
    decimals: 5,
    logo: "https://cdn.dexscreener.com/cms/images/33effe52dd5b1f6574ca5baaca9c02fecdecb557607a2a72889ceb0537eae9be?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
  {
    mint: "9BB6NFEcjBCtnNLFko2FqVQBq8HHM13kCyYcdQbgpump",
    symbol: "FARTCOIN",
    name: "Fartcoin",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/9af5672845c89585e9ff1e3b26a640090324aa4d92222052d1043e60ef8182de?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
  {
    mint: "2qEHjDLDLbuBgRYvsxhc5D6uDWAivNFZGan56P1tpump",
    symbol: "PNUT",
    name: "Peanut the Squirrel",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/778498984ea5b6eb7c9d74e1e81a2547c88a41ae80f6c840c94a7c3b7829bcd5?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
  {
    mint: "Ai66LHZG9MCzg1WKdawwqduVAXpNDUuV8M3uyq5ppump",
    symbol: "CATE",
    name: "Catecoin",
    decimals: 6,
    logo: "https://cdn.dexscreener.com/cms/images/_aILGflqFiJQJ4A-?width=800&height=800&quality=95&format=auto",
    verified: true,
    tags: ["verified", "community", "meme"],
    liquidity: 0,
  },
];
